version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "back/scaffm8"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "front/scaffm8"
    schedule:
      interval: "weekly"
      # Check for npm updates on Sundays
      day: "sunday"