export const urlBackend = process.env.REACT_APP_URL_BACKEND ?? ''
export const urlFrontend = process.env.REACT_APP_URL_FRONTEND ?? ''
export const platformName = process.env.REACT_APP_PLATFORM_NAME ?? ''
export const UserLocalStorageKey = 'user'
export const GoogleMapsApiKey = process.env.REACT_APP_GOOGLE_MAPS_API_KEY ?? ''
