name: Front-end crockett

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "front/crockett/**"

defaults:
  run:
    working-directory: front/crockett

env:
  AWS_REGION: us-east-1 # don't move
  ACCOUNT_ID: "526382770485" # don't move
  REACT_APP_URL_BACKEND_DEV: "https://crockett-back.scaffm8.co.nz"
  REACT_APP_URL_FRONTEND_DEV: "https://crockett.scaffm8.net"
  REACT_APP_PLATFORM_NAME: "Crockett Industries"
  REACT_APP_ID: "crockett"
  REACT_APP_URL_BACKEND_PDN: "https://crockett-back.scaffm8.co.nz"
  REACT_APP_URL_FRONTEND_PDN: "https://crockett.scaffm8.co.nz"
  PORT: 3000

  INFRA_STACK_NAME: StackCrockett
  S3_BUCKET_FRONT: crockett-526382770485
  SITE_SUB_DOMAIN: crockett

jobs:
  ci:
    name: continue integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials from net account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CLOUD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_CLOUD }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_CLOUD }}
          aws-region: ${{ env.AWS_REGION }}

  dev:
    needs: ci
    name: Environment Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Tag Number
        id: tag-number
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check Tag Release
        env:
          RELEASE_VERSION: ${{ steps.tag-number.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Configure AWS credentials from dev account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CLOUD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_CLOUD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: install dependencies 
        run: npm install
      
      - name: Install dependencies and aws cdk
        working-directory: infra/
        run: |
          sudo npm install -g aws-cdk
          npm install

      - name: Deploy S3
        working-directory: infra/
        env:
          INFRA_CONFIG_FRONT: InfraStackS3
          INFRA_STACK_NAME: ${{ env.INFRA_STACK_NAME }}-dev
          S3_BUCKET: ${{ env.S3_BUCKET_FRONT }}-dev
          S3_VERSIONING: true
          DOMAIN_NAME: 'scaffm8.net'
          HOSTED_ZONE_ID: "Z07176612B26L8JDY4T96"
        run: |
          REGION=${{ env.AWS_REGION }}
          ACCOUNT_ID=${{ env.ACCOUNT_ID }}
          INFRA_CONFIG_FRONT=${{ env.INFRA_CONFIG_FRONT }}
          INFRA_STACK_NAME=${{ env.INFRA_STACK_NAME }}
          S3_BUCKET=${{ env.S3_BUCKET }}
          S3_VERSIONING=${{ env.S3_VERSIONING }}
          SITE_SUB_DOMAIN=${{ env.SITE_SUB_DOMAIN }}
          DOMAIN_NAME=${{ env.DOMAIN_NAME }}
          HOSTED_ZONE_ID=${{ env.HOSTED_ZONE_ID }}
          cdk deploy ${{ env.INFRA_STACK_NAME }} -c config=${{ env.INFRA_CONFIG_FRONT }} --require-approval never
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_PORT: ${{ env.PORT }}
          envkey_REACT_APP_URL_BACKEND: ${{ env.REACT_APP_URL_BACKEND_DEV }}
          envkey_REACT_APP_URL_FRONTEND: ${{ env.REACT_APP_URL_FRONTEND_DEV }}
          envkey_REACT_APP_PLATFORM_NAME: ${{ env.REACT_APP_PLATFORM_NAME }}
          envkey_REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
          directory: front/${{ env.REACT_APP_ID }}
          fail_on_empty: true

      - name: Build
        run: npm run build

      - name: Deploy
        run: aws s3 sync ./build s3://${{ env.S3_BUCKET_FRONT }}-dev

  pdn:
    needs: dev
    name: Environment Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Tag Number
        id: tag-number
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check Tag Release
        env:
          RELEASE_VERSION: ${{ steps.tag-number.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Configure AWS credentials from dev account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CLOUD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_CLOUD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: install dependencies 
        run: npm install
      
      - name: Install dependencies and aws cdk
        working-directory: infra/
        run: |
          sudo npm install -g aws-cdk
          npm install

      - name: Deploy S3
        working-directory: infra/
        env:
          INFRA_CONFIG_FRONT: InfraStackS3 
          INFRA_STACK_NAME:  ${{ env.INFRA_STACK_NAME }}-pdn
          S3_BUCKET: ${{ env.S3_BUCKET_FRONT }}-pdn
          S3_VERSIONING: true
          DOMAIN_NAME: 'scaffm8.co.nz'
          HOSTED_ZONE_ID: "Z0793601ORQ08J23KVBA"
        run: |
          REGION=${{ env.AWS_REGION }}
          ACCOUNT_ID=${{ env.ACCOUNT_ID }}
          INFRA_CONFIG_FRONT=${{ env.INFRA_CONFIG_FRONT }}
          INFRA_STACK_NAME=${{ env.INFRA_STACK_NAME }}
          S3_BUCKET=${{ env.S3_BUCKET }}
          S3_VERSIONING=${{ env.S3_VERSIONING }}
          SITE_SUB_DOMAIN=${{ env.SITE_SUB_DOMAIN }}
          DOMAIN_NAME=${{ env.DOMAIN_NAME }}
          HOSTED_ZONE_ID=${{ env.HOSTED_ZONE_ID }}
          cdk deploy ${{ env.INFRA_STACK_NAME }} -c config=${{ env.INFRA_CONFIG_FRONT }} --require-approval never
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_PORT: ${{ env.PORT }}
          envkey_REACT_APP_URL_BACKEND: ${{ env.REACT_APP_URL_BACKEND_PDN }}
          envkey_REACT_APP_URL_FRONTEND: ${{ env.REACT_APP_URL_FRONTEND_PDN }}
          envkey_REACT_APP_PLATFORM_NAME: ${{ env.REACT_APP_PLATFORM_NAME }}
          envkey_REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
          directory: front/${{ env.REACT_APP_ID }}
          fail_on_empty: true

      - name: Build
        run: npm run build

      - name: Deploy
        run: aws s3 sync ./build s3://${{ env.S3_BUCKET_FRONT }}-pdn
